//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_CITIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public string aNumber { get; set; }
        public string direction { get; set; }
        public string bNumber { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<decimal> cellLong { get; set; }
        public Nullable<decimal> cellLat { get; set; }
        public long ID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
